font_family  Iosevka Term
font_size            17.0
disable_ligatures  cursor

mouse_hide_wait -1.0

scrollback_lines 1000000

enable_audio_bell      no

map ctrl+return new_os_window_with_cwd

shell nu

include catppuccin-mocha-theme.conf
