FROM debian:unstable-20251020 as install-base

# https://stackoverflow.com/a/72851168
RUN \
  --mount=type=bind,src=containers/base/packagelist,dst=/packagelist \
  --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
  --mount=target=/var/cache/apt,type=cache,sharing=locked \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  apt-get update && \
  xargs apt-get -y --no-install-recommends install < /packagelist

RUN \
  passwd -d root && \
  useradd -u 1000 -m -s /usr/bin/fish boxuser

# <helix-grammar-build>
FROM install-base as helix-grammar-build

# We replicate this so that we don't depend on packagelist
RUN \
  --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
  --mount=target=/var/cache/apt,type=cache,sharing=locked \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  apt-get update && \
  apt-get -y --no-install-recommends install git gcc g++ ca-certificates hx

USER 1000:1000
WORKDIR /home/boxuser

RUN hx --grammar fetch && hx --grammar build
# </helix-grammar-build>


FROM install-base

USER 1000:1000
WORKDIR /home/boxuser

COPY --from=helix-grammar-build /home/boxuser/.config/helix/runtime/grammars .config/helix/runtime/grammars

COPY --chown=1000:1000 fish .config/fish
COPY --chown=1000:1000 starship.toml .config/
COPY --chown=1000:1000 helix .config/helix

# Sometimes it's hx, sometimes it's helix
RUN \
  printf "%s\n" \
    "function get-helix-editor-name; echo hx; end" \
    > .config/fish/functions/get-helix-editor-name.fish
    

ENTRYPOINT ["/usr/bin/fish"]


