ARG BASE_IMAGE=docker.io/library/archlinux:base-20251019.0.436919

FROM $BASE_IMAGE as mirror-base

RUN \
  echo 'Server = https://archive.archlinux.org/repos/2025/11/02/$repo/os/$arch' \
    > /etc/pacman.d/mirrorlist

RUN \
  --mount=target=/var/lib/pacman/sync,type=cache,sharing=locked \
  --mount=target=/var/cache/pacman/pkg,type=cache,sharing=locked \
  yes | pacman -Sy
    
FROM mirror-base as install-base

RUN \
  --mount=type=bind,src=containers/base/packagelist,dst=/packagelist \
  --mount=target=/var/lib/pacman/sync,type=cache,sharing=locked \
  --mount=target=/var/cache/pacman/pkg,type=cache,sharing=locked \
  yes | pacman --needed -Syu $(< /packagelist)

RUN \
  echo root | passwd -s root && \
  useradd -u 1000 -m -s /usr/bin/fish boxuser

# <helix-grammar-build>
FROM mirror-base as helix-grammar-build

# We replicate this so that we don't depend on packagelist
RUN \
  --mount=type=bind,src=containers/base/packagelist,dst=/packagelist \
  --mount=target=/var/lib/pacman/sync,type=cache,sharing=locked \
  --mount=target=/var/cache/pacman/pkg,type=cache,sharing=locked \
  yes | pacman --needed -Syu git gcc helix

USER 1000:1000
WORKDIR /home/boxuser
ENV HOME=/home/boxuser

RUN helix --grammar fetch && helix --grammar build
# </helix-grammar-build>


FROM install-base

USER 1000:1000
WORKDIR /home/boxuser

COPY --chown=1000:1000 --from=helix-grammar-build /home/boxuser/.config/helix/runtime/grammars .config/helix/runtime/grammars

COPY --chown=1000:1000 fish .config/fish
COPY --chown=1000:1000 starship.toml .config/
COPY --chown=1000:1000 helix .config/helix

ENTRYPOINT ["/usr/bin/fish"]


